/**
 * Boot-splash (Plymouth) theme generators for the cold-boot chain (POL-7).
 *
 * On cold boot the wall would otherwise show raw kernel/systemd console text until the compositor
 * comes up — and the same raw text on the way DOWN at shutdown/reboot. This module generates a small
 * branded **Plymouth** theme — a scalable vector logo, the build version + hostname, and a LIVE
 * status line — shown continuously from early boot until the player paints, AND again through
 * shutdown/reboot (the script keys off `Plymouth.GetMode()` to show "Starting up" vs "Shutting
 * down"/"Restarting"). No kernel/console text at either end (see docs/ARCHITECTURE.md "Boot splash").
 *
 * Everything here is a pure string generator (like ./templates.ts): the agent single binary carries
 * the whole theme as source and `install.ts` writes it out + rasterises the SVGs to PNG at provision
 * time. That keeps the zero-touch `curl|sh` path (which downloads ONLY the binary — D35) able to lay
 * down the splash with no extra assets to fetch.
 *
 * Why a *script* theme, not a static image (answering the "can it be live?" question): Plymouth's
 * `script` plugin gives us live callbacks — `SetUpdateStatusFunction` (systemd's "Starting …" unit
 * messages as boot advances), `SetBootProgressFunction` (a 0..1 fraction), and `SetMessageFunction`
 * (anything pushed with `plymouth message --text=…`, e.g. by the agent). So the splash is a live
 * boot readout, not a frozen picture. The version + hostname are known at provision time and baked
 * into the vector stamp; they can also be refreshed live via `plymouth message`.
 *
 * Swappability (POL-7 acceptance): the logo is a plain **SVG** (`logo.svg`) rasterised to `logo.png`
 * at install. Drop in the final designed asset (SVG preferred, or a pre-rendered `logo.png`) and
 * re-run `polyptic-agent setup` — nothing else changes. It is vector, so it scales to any panel.
 */

/** Installed theme name (what `plymouth-set-default-theme` selects). */
export const PLYMOUTH_THEME_NAME = "polyptic";
/** Where the theme's files live once installed. */
export const PLYMOUTH_THEME_DIR = `/usr/share/plymouth/themes/${PLYMOUTH_THEME_NAME}`;

/** systemd drop-in that makes plymouth-quit retain the last splash frame (seamless handoff). */
export const PLYMOUTH_QUIT_DROPIN =
  "/etc/systemd/system/plymouth-quit.service.d/10-polyptic-retain-splash.conf";

const MANAGED = "generated by `polyptic-agent setup` — re-running setup may overwrite this file.";

// ── palette (the DARK variant of the Console Boot Splash design; 8-bit sRGB) ─────────────────────
// A wall powers on in a room that is often dim; a dark splash avoids a jarring white flash and
// matches the product's dark surfaces. Light-on-white is the design's alternate (not shipped).
const COLORS = {
  bg: "#0b0b0d", // page background
  holder: "#fafafa", // rounded logo holder
  glyph: "#161618", // the mark inside the holder
  glyphOpacity: 0.55, // side panels of the mark (centre bar is full opacity)
  wordmark: "#fafafa",
  subtitle: "#71717a",
  status: "#a1a1aa", // the live boot-status line
  stampHost: "#4b4d54",
  stampVersion: "#a1a1aa",
  track: "#26262b", // progress-bar track
  accent: "#2563eb", // progress-bar fill
} as const;

/** #rrggbb → "r, g, b" as Plymouth 0..1 floats (its colour args are normalised). */
function toPlymouthRgb(hex: string): string {
  const h = hex.replace("#", "");
  const r = parseInt(h.slice(0, 2), 16) / 255;
  const g = parseInt(h.slice(2, 4), 16) / 255;
  const b = parseInt(h.slice(4, 6), 16) / 255;
  const f = (n: number): string => n.toFixed(3);
  return `${f(r)}, ${f(g)}, ${f(b)}`;
}

// ── asset specs: which SVGs to rasterise, and to what pixel width (aspect preserved) ─────────────
// Rasterised generously above the on-screen size so the script's proportional down-scale stays crisp
// on a 4K panel. `height` is only set where the aspect must be forced (the thin solid bars).
export interface SplashAsset {
  /** Base filename (without extension) under the theme dir. */
  base: string;
  /** SVG source. */
  svg: string;
  /** Rasterise width in px. */
  width: number;
  /** Rasterise height in px (bars only — omit to preserve the SVG aspect ratio). */
  height?: number;
}

export interface StampParams {
  hostname: string;
  version: string;
}

/**
 * The placeholder logo — the Polyptic mark (two hinged side panels + a squared centre panel on a
 * rounded holder, matching packages/console Logo.vue) plus the wordmark + "display node" subtitle.
 * This is THE swappable asset (POL-7): replace logo.svg (or logo.png) with the final designed lockup
 * and re-run setup. Vector, so it scales to any panel.
 */
export function logoSvg(): string {
  const holder = 136;
  const holderX = (640 - holder) / 2; // 252
  // glyph: the 32×32 Logo.vue viewBox scaled to 98px, centred in the 136px holder.
  const glyphScale = 98 / 32;
  const glyphX = holderX + (holder - 98) / 2;
  const glyphY = (holder - 98) / 2;
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- ${MANAGED} Placeholder Polyptic logo lockup — swap for the final designed asset (keep it SVG). -->
<svg xmlns="http://www.w3.org/2000/svg" width="640" height="280" viewBox="0 0 640 280" fill="none">
  <rect x="${holderX}" y="0" width="${holder}" height="${holder}" rx="33" fill="${COLORS.holder}"/>
  <g transform="translate(${glyphX} ${glyphY}) scale(${glyphScale})">
    <polygon points="6.6,11 12.3,8.2 12.3,23.8 6.6,21" fill="${COLORS.glyph}" opacity="${COLORS.glyphOpacity}"/>
    <polygon points="25.4,11 19.7,8.2 19.7,23.8 25.4,21" fill="${COLORS.glyph}" opacity="${COLORS.glyphOpacity}"/>
    <rect x="13.1" y="8" width="5.8" height="16" fill="${COLORS.glyph}"/>
  </g>
  <text x="320" y="216" text-anchor="middle" font-family="'Geist','Inter','Helvetica Neue',Arial,'DejaVu Sans',sans-serif" font-size="52" font-weight="600" letter-spacing="-1.4" fill="${COLORS.wordmark}">Polyptic</text>
  <text x="320" y="252" text-anchor="middle" font-family="'Geist Mono','DejaVu Sans Mono',monospace" font-size="16" font-weight="500" letter-spacing="5" fill="${COLORS.subtitle}">DISPLAY NODE</text>
</svg>
`;
}

/**
 * The bottom stamp: "<hostname> · v<version>", rendered from the build + host so the two facts Alex
 * called out are on-screen from early boot. Baked at provision time; also refreshable live via
 * `plymouth message`.
 */
export function stampSvg(p: StampParams): string {
  // Basic XML-escape so an exotic hostname can't break the SVG.
  const esc = (s: string): string =>
    s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
  const host = esc(p.hostname);
  const version = esc(p.version.startsWith("v") ? p.version : `v${p.version}`);
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- ${MANAGED} hostname + build version stamp. -->
<svg xmlns="http://www.w3.org/2000/svg" width="640" height="30" viewBox="0 0 640 30" fill="none">
  <text x="320" y="22" text-anchor="middle" font-family="'Geist Mono','DejaVu Sans Mono',monospace" font-size="20" letter-spacing="0.5">
    <tspan fill="${COLORS.stampHost}">${host}</tspan><tspan fill="${COLORS.stampHost}">   ·   </tspan><tspan fill="${COLORS.stampVersion}">${version}</tspan>
  </text>
</svg>
`;
}

function barSvg(fill: string): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- ${MANAGED} -->
<svg xmlns="http://www.w3.org/2000/svg" width="260" height="4" viewBox="0 0 260 4" fill="none">
  <rect x="0" y="0" width="260" height="4" rx="2" fill="${fill}"/>
</svg>
`;
}

/** All SVG assets the theme needs, with their rasterise targets. */
export function splashAssets(stamp: StampParams): SplashAsset[] {
  return [
    { base: "logo", svg: logoSvg(), width: 1600 },
    { base: "stamp", svg: stampSvg(stamp), width: 1200 },
    { base: "bar-track", svg: barSvg(COLORS.track), width: 520, height: 8 },
    { base: "bar-fill", svg: barSvg(COLORS.accent), width: 520, height: 8 },
  ];
}

/** The theme descriptor Plymouth reads (`<name>.plymouth`). */
export function plymouthTheme(): string {
  return `# ${PLYMOUTH_THEME_NAME}.plymouth — ${MANAGED}
[Plymouth Theme]
Name=Polyptic
Description=Polyptic display node — branded boot splash with a live status line.
ModuleName=script

[script]
ImageDir=${PLYMOUTH_THEME_DIR}
ScriptFile=${PLYMOUTH_THEME_DIR}/${PLYMOUTH_THEME_NAME}.script
`;
}

/**
 * The Plymouth `script`-plugin program. Draws the centred logo, an animated progress bar, the live
 * boot-status line, and the hostname/version stamp — resolution-independent (everything is sized off
 * Window.GetWidth()/GetHeight()). Colours are baked from the palette above.
 *
 * NOTE: the Plymouth scripting language is a small C/JS-like DSL (fun/if/while, `.` members, colour
 * args as 0..1 floats). Text from Image.Text renders at the plugin's default point size, so we
 * proportionally Scale() it for wall legibility rather than depend on the (version-varying) font
 * argument.
 */
export function plymouthScript(): string {
  return `# ${PLYMOUTH_THEME_NAME}.script — ${MANAGED}
#
# A LIVE boot splash: the logo + version/host stamp are static branding; the status line and the
# progress bar update from Plymouth's boot callbacks as systemd brings the box up.

# ── background (${COLORS.bg}) ──────────────────────────────────────────────────
Window.SetBackgroundTopColor(${toPlymouthRgb(COLORS.bg)});
Window.SetBackgroundBottomColor(${toPlymouthRgb(COLORS.bg)});

sw = Window.GetWidth();
sh = Window.GetHeight();
cx = sw / 2;

# The same theme covers BOTH cold boot AND machine shutdown/reboot (systemd runs plymouth on the way
# down too), so no kernel/console text shows at either end. Pick the right status + only show the
# boot progress bar when actually booting.
boot_mode = Plymouth.GetMode();
initial_status = "Starting up";
show_bar = 1;
if (boot_mode == "shutdown") {
  initial_status = "Shutting down";
  show_bar = 0;
}
if (boot_mode == "reboot") {
  initial_status = "Restarting";
  show_bar = 0;
}
if (boot_mode == "updates") {
  initial_status = "Applying updates";
}

# ── logo lockup (centred, ~30% of screen width) ──────────────────────────────
logo.image = Image("logo.png");
logo.have = 0;
if (logo.image.GetWidth() > 0) {
  logo.have = 1;
  logo.scale = (sw * 0.30) / logo.image.GetWidth();
  logo.img = logo.image.Scale(logo.image.GetWidth() * logo.scale, logo.image.GetHeight() * logo.scale);
  logo.sprite = Sprite(logo.img);
  logo.x = cx - logo.img.GetWidth() / 2;
  logo.y = sh * 0.30 - logo.img.GetHeight() / 2;
  logo.sprite.SetX(logo.x);
  logo.sprite.SetY(logo.y);
  logo.sprite.SetZ(10);
  content_bottom = logo.y + logo.img.GetHeight();
} else {
  content_bottom = sh * 0.45;
}

# ── progress bar (determinate; driven by SetBootProgressFunction) ─────────────
bar.track_img = Image("bar-track.png");
bar.fill_img = Image("bar-fill.png");
bar.w = sw * 0.135;
bar.h = sh * 0.0037;
if (bar.h < 3) {
  bar.h = 3;
}
bar.x = cx - bar.w / 2;
bar.y = content_bottom + sh * 0.10;
bar.have = 0;
if (show_bar == 1) {
  if (bar.track_img.GetWidth() > 0) {
    bar.have = 1;
    bar.track = Sprite(bar.track_img.Scale(bar.w, bar.h));
    bar.track.SetX(bar.x);
    bar.track.SetY(bar.y);
    bar.track.SetZ(11);
    bar.fill = Sprite();
    bar.fill.SetX(bar.x);
    bar.fill.SetY(bar.y);
    bar.fill.SetZ(12);
  }
}

fun draw_fill(p) {
  if (bar.have == 1) {
    if (p < 0) {
      p = 0;
    }
    if (p > 1) {
      p = 1;
    }
    w = bar.w * p;
    if (w < 1) {
      w = 1;
    }
    bar.fill.SetImage(bar.fill_img.Scale(w, bar.h));
  }
}
draw_fill(0);

# ── live boot-status line ─────────────────────────────────────────────────────
status.y = bar.y + sh * 0.055;
status.sprite = Sprite();
status.text = "";
fun set_status(text) {
  if (text != status.text) {
    status.text = text;
    img = Image.Text(text, ${toPlymouthRgb(COLORS.status)});
    k = sh / 620;
    if (k < 1) {
      k = 1;
    }
    img = img.Scale(img.GetWidth() * k, img.GetHeight() * k);
    # keep a long systemd status string from spilling past the panel edges
    if (img.GetWidth() > sw * 0.8) {
      img = img.Scale(sw * 0.8, img.GetHeight() * (sw * 0.8) / img.GetWidth());
    }
    status.sprite.SetImage(img);
    status.sprite.SetX(cx - img.GetWidth() / 2);
    status.sprite.SetY(status.y);
    status.sprite.SetZ(11);
  }
}
set_status(initial_status);

# ── hostname / version stamp (bottom-centre) ─────────────────────────────────
stamp.image = Image("stamp.png");
if (stamp.image.GetHeight() > 0) {
  # size by height (~2.6% of screen) so the text reads the same on any panel
  stamp.scale = (sh * 0.026) / stamp.image.GetHeight();
  stamp.img = stamp.image.Scale(stamp.image.GetWidth() * stamp.scale, stamp.image.GetHeight() * stamp.scale);
  stamp.sprite = Sprite(stamp.img);
  stamp.sprite.SetX(cx - stamp.img.GetWidth() / 2);
  stamp.sprite.SetY(sh - sh * 0.06 - stamp.img.GetHeight() / 2);
  stamp.sprite.SetZ(11);
}

# ── live callbacks ────────────────────────────────────────────────────────────
target_progress = 0;
progress = 0;

Plymouth.SetBootProgressFunction(fun (duration, prog) {
  target_progress = prog;
});

Plymouth.SetUpdateStatusFunction(fun (text) {
  set_status(text);
});

# ease the bar towards the latest target on every refresh so it never jumps
Plymouth.SetRefreshFunction(fun () {
  progress = progress + (target_progress - progress) * 0.08;
  draw_fill(progress);
});

# operator/agent pushes: \`plymouth message --text="…"\` shows just under the status line
message.sprite = Sprite();
message.y = status.y + sh * 0.05;
Plymouth.SetMessageFunction(fun (text) {
  img = Image.Text(text, ${toPlymouthRgb(COLORS.status)});
  k = sh / 700;
  if (k < 1) {
    k = 1;
  }
  img = img.Scale(img.GetWidth() * k, img.GetHeight() * k);
  message.sprite.SetImage(img);
  message.sprite.SetX(cx - img.GetWidth() / 2);
  message.sprite.SetY(message.y);
  message.sprite.SetZ(11);
});
`;
}

/** The plymouth-quit drop-in: retain the last splash frame so sway can paint over it (no flash). */
export function plymouthQuitDropin(): string {
  return `# ${MANAGED}
# Keep the final splash frame on screen when Plymouth quits, so the compositor paints straight over
# it with no flash of a blank console between the splash and the player (POL-7 clean hand-off).
[Service]
ExecStart=
ExecStart=-/usr/bin/plymouth quit --retain-splash
`;
}

// ── kernel cmdline merge (pure + testable) ───────────────────────────────────────────────────────

/** Tokens that route boot output to the splash instead of the console. */
export const SPLASH_CMDLINE_TOKENS = ["quiet", "splash", "plymouth.ignore-serial-consoles"] as const;

/**
 * Ensure `GRUB_CMDLINE_LINUX_DEFAULT` in an /etc/default/grub body contains every splash token,
 * without disturbing anything else the operator set. Returns the (possibly unchanged) new body.
 * Idempotent — running it twice is a no-op. If the key is absent it is appended.
 */
export function mergeGrubCmdline(body: string, tokens: readonly string[] = SPLASH_CMDLINE_TOKENS): string {
  const key = "GRUB_CMDLINE_LINUX_DEFAULT";
  const lineRe = new RegExp(`^(\\s*${key}\\s*=\\s*)(["'])([\\s\\S]*?)\\2(\\s*)$`, "m");
  const m = lineRe.exec(body);
  if (!m) {
    const existing = new Set<string>();
    const added = tokens.filter((t) => !existing.has(t));
    const line = `${key}="${added.join(" ")}"`;
    return body.endsWith("\n") || body.length === 0 ? `${body}${line}\n` : `${body}\n${line}\n`;
  }
  const [, prefix, quote, current] = m;
  const present = new Set((current ?? "").split(/\s+/).filter((t) => t.length > 0));
  const missing = tokens.filter((t) => !present.has(t));
  if (missing.length === 0) return body; // already complete
  const merged = [...(current ?? "").split(/\s+/).filter((t) => t.length > 0), ...missing].join(" ");
  return body.replace(lineRe, `${prefix}${quote}${merged}${quote}`);
}

/**
 * Ensure a bare kernel cmdline file (Raspberry Pi / u-boot `cmdline.txt`, a single space-separated
 * line) contains every splash token. Returns the (possibly unchanged) new body.
 */
export function mergeCmdlineTxt(body: string, tokens: readonly string[] = SPLASH_CMDLINE_TOKENS): string {
  const line = body.split(/\r?\n/).find((l) => l.trim().length > 0) ?? "";
  const present = new Set(line.split(/\s+/).filter((t) => t.length > 0));
  const missing = tokens.filter((t) => !present.has(t));
  if (missing.length === 0) return body;
  const merged = [...line.split(/\s+/).filter((t) => t.length > 0), ...missing].join(" ");
  if (line.length === 0) return `${merged}\n`;
  return body.replace(line, merged);
}
