#!/bin/sh
# Render the LOCAL GRUB menu for one arch of the boot medium → stdout (POL-63). This is the menu a
# box gets when the wired chain to the server is unreachable — the Wi-Fi boot path — so it must be
# COMPLETE offline: local kernel + initrd-wifi paths on the medium, and a fully-baked cmdline
# (mirroring the server's bootKernelCmdline in packages/server/src/provision.ts, entry for entry).
#
#   usage: render-local-grub.sh <arch> <slot> <hostport> <imageId> [token]
#
# Written by THREE writers, one renderer: build-boot-medium.sh (at build), update-poll.sh (slot
# switches on image updates), offload.sh (copying the payload to an ESP). Everything is baked
# static — arch, slot, image id — because GRUB variables cost context bugs (D61) and the file is
# regenerated wholesale whenever any of it changes. The current slot/image are PARSEABLE back out
# of the header line, which is how update-poll knows what a medium is running.
#
# The `live` entry pins root= to builds/<imageId>/ so the kernel on the medium always meets the
# /lib/modules it was built with. `live-latest` is the recovery entry for a box offline longer than
# the depot's retention: the ACTIVE image with a possibly mismatched kernel — degraded, but it gets
# the box far enough online for update-poll to refresh the medium and reboot into a matched pair.

ARCH="${1:?usage: render-local-grub.sh <arch> <slot> <hostport> <imageId> [token]}"
SLOT="${2:?missing slot}"
HOSTPORT="${3:?missing hostport}"
IMAGE_ID="${4:?missing imageId}"
TOKEN="${5:-}"

BOOT="/polyptic/boot/$ARCH/$SLOT"
# Where build-boot-medium.sh / offload.sh bake the POL-47 theme (theme.txt + logo.png + bg.png) so
# the offline menu can paint the branded splash with no network to fetch it from (POL-74).
THEME_DIR="/polyptic/boot/theme"
tok=""
[ -z "$TOKEN" ] || tok=" polyptic.token=$TOKEN"
# bootKernelCmdline's tail, verbatim (multipath=off .. plymouth.ignore-serial-consoles).
common="rd.overlay=1 ip=dhcp rd.neednet=1 polyptic.base=http://$HOSTPORT polyptic.server_url=ws://$HOSTPORT/agent$tok multipath=off quiet splash plymouth.ignore-serial-consoles"
pinned="root=live:http://$HOSTPORT/dist/image/$ARCH/builds/$IMAGE_ID/rootfs.squashfs $common"
latest="root=live:http://$HOSTPORT/dist/image/$ARCH/rootfs.squashfs $common"

# Entry names + tone mirror the server menu (provision.ts buildBootGrubCfg, POL-47/D65): wall-facing
# strings stay plain English; the technical detail belongs to the entries nobody picks by accident.
cat <<EOF
# polyptic-local arch=$ARCH slot=$SLOT image=$IMAGE_ID
# Local boot menu (POL-63): kernel + initrd read from THIS medium, the OS image streamed from the
# control plane (over Wi-Fi via polyptic/wifi.conf, or any wire that appears). Regenerated by
# update-poll on image updates — do not hand-edit; edits are overwritten at the next update.
#
# Paint the Polyptic splash (POL-47) from the theme baked onto THIS medium (POL-74) — the wired path
# fetches theme.txt from the server, but the offline path has no server, so the medium carries its
# own copy. Same guard discipline as the server's bootGfxPreamble (packages/server/src/boot-theme.ts):
# the whole block hangs off loadfont, and \`set theme\` only fires if the theme was actually baked,
# so a LEAN or theme-less medium still boots to a plain menu on the correct dark background.
# ALL THREE files are checked (POL-87, then POL-130): the theme references logo.png AND bg.png —
# bg.png is the desktop-image GRUB 2.12's gfxmenu insists on scaling at every draw, and a theme
# without one (or with a bitmap that is missing) leaves "error: null src bitmap ... Press any key
# to continue" on a screen that has no keyboard the moment the menu boots its entry. A medium
# missing ANY of the three degrades to the plain menu on the correct dark background, which boots
# silently. Nested ifs, not -a: plain [ -f ] is the only test form every GRUB build has.
if loadfont (memdisk)/fonts/unicode.pf2 ; then
  insmod all_video
  insmod gfxterm
  insmod gfxterm_background
  insmod png
  insmod gfxmenu
  set gfxmode=auto
  set gfxpayload=keep
  terminal_output gfxterm
  background_color "#0b0b0d"
  if [ -f (\$root)$THEME_DIR/theme.txt ]; then if [ -f (\$root)$THEME_DIR/logo.png ]; then if [ -f (\$root)$THEME_DIR/bg.png ]; then set theme=(\$root)$THEME_DIR/theme.txt ; fi ; fi ; fi
fi
set timeout=5
set default=live
menuentry "Polyptic" --id live {
  echo "Starting Polyptic ..."
  linux  $BOOT/vmlinuz $pinned
  initrd $BOOT/initrd
}
menuentry "Polyptic (newest image - use after a long time offline)" --id live-latest {
  echo "Starting Polyptic with the newest image ..."
  linux  $BOOT/vmlinuz $latest
  initrd $BOOT/initrd
}
menuentry "Set up this screen to start without the USB stick" --id offload {
  echo "Setting up this screen ..."
  linux  $BOOT/vmlinuz $pinned polyptic.offload=1
  initrd $BOOT/initrd
}
menuentry "Debug console" --id debug {
  echo "Starting Polyptic with a root shell on tty9 (Ctrl+Alt+F9) ..."
  linux  $BOOT/vmlinuz $pinned systemd.debug-shell=1
  initrd $BOOT/initrd
}
EOF
exit 0
