#!/bin/sh
# ExecStart for polyptic-timesync-conf.service (POL-148). Points systemd-timesyncd at the NTP server
# baked into the boot cmdline, so a diskless box disciplines its clock instead of free-running off the
# RTC (one fpd-ago box drifted an hour ahead and silently broke a relative-range dashboard).
#
# The live image ships NO time client until POL-148 (a real box reads `NTP service: n/a`); the build
# installs systemd-timesyncd and enables it, and THIS helper writes its server before it starts. The
# daemon runs with CAP_SYS_TIME, so it sets the clock without the unprivileged kiosk user, and the
# kernel's 11-minute mode carries the corrected time back to the RTC once synced.
#
# The NTP host comes from the kernel command line, first match wins:
#   polyptic.ntp=<host>          the server bakes this (the boot host; POL-148 provision.ts)
#   polyptic.server_url=ws://H…  fallback for OLDER baked media with no polyptic.ntp — the NTP server
#                                is reachable at the same host on UDP/123 via the Traefik UDP route.
# With NO host derivable, we write nothing and exit 0: timesyncd then keeps its packaged default and
# the box simply doesn't sync — never a boot failure over a clock (non-negotiable #4, zero-click).
#
# Pure + overridable for the test: POLYPTIC_CMDLINE_FILE (default /proc/cmdline) and
# POLYPTIC_TIMESYNC_CONF_DIR (default the runtime drop-in dir timesyncd reads before /etc/usr).
set -u
CMDLINE_FILE="${POLYPTIC_CMDLINE_FILE:-/proc/cmdline}"
CONF_DIR="${POLYPTIC_TIMESYNC_CONF_DIR:-/run/systemd/timesyncd.conf.d}"

[ -r "$CMDLINE_FILE" ] || exit 0

ntp=""; server_url=""
IFS= read -r line < "$CMDLINE_FILE" || line=""
for tok in $line; do            # intentional unquoted split on IFS whitespace
  case "$tok" in
    polyptic.ntp=*)        [ -z "$ntp" ]        && ntp="${tok#polyptic.ntp=}" ;;
    polyptic.server_url=*) [ -z "$server_url" ] && server_url="${tok#polyptic.server_url=}" ;;
  esac
done

# Fallback: derive the host out of the ws(s):// agent URL (strip scheme, then anything from the first
# '/', ':' or '@' — i.e. path, port, or userinfo). Pure shell, no dirname/sed dependency (the POL-78
# lesson: the initramfs shipped no `dirname`).
if [ -z "$ntp" ] && [ -n "$server_url" ]; then
  host="${server_url#*://}"     # drop scheme
  host="${host%%/*}"            # drop path
  host="${host##*@}"            # drop userinfo
  host="${host%%:*}"            # drop port
  ntp="$host"
fi

[ -n "$ntp" ] || exit 0

mkdir -p "$CONF_DIR"
tmp="$(mktemp "$CONF_DIR/10-polyptic.conf.XXXXXX")"
{
  printf '# Generated by polyptic-timesync-conf.service (POL-148); regenerated every boot.\n'
  printf '[Time]\n'
  printf 'NTP=%s\n' "$ntp"
} > "$tmp"
chmod 0644 "$tmp"
mv -f "$tmp" "$CONF_DIR/10-polyptic.conf"
exit 0
