#!/bin/sh
# ExecStart for polyptic-agent-env.service (POL-33). Composes /run/polyptic/agent.env ATOMICALLY from the
# derived stable machine id + the runtime cmdline config. Runs as root at boot, ordered Before=greetd, so
# the file exists before the kiosk user's `systemd --user` starts polyptic-agent.service (which reads it
# via an EnvironmentFile drop-in). Real env vars from this file beat /etc/polyptic/agent.toml, whose
# applyConfigFileToEnv() only fills UNSET vars, so the per-boot cmdline always wins with no agent change.
set -u
LIB="${POLYPTIC_LIB_DIR:-/usr/local/lib/polyptic}"
RUN_DIR="${POLYPTIC_RUN_DIR:-/run/polyptic}"
ENV_FILE="${POLYPTIC_ENV_FILE:-$RUN_DIR/agent.env}"
OWNER="${POLYPTIC_ENV_OWNER:-root:kiosk}"   # readable by the kiosk --user manager, not world

mkdir -p "$RUN_DIR"; chmod 0755 "$RUN_DIR"
mid="$(sh "$LIB/derive-machine-id.sh")"

tmp="$(mktemp "$ENV_FILE.XXXXXX")"
{
  printf '# Generated by polyptic-agent-env.service, regenerated every boot; do not edit.\n'
  printf 'POLYPTIC_MACHINE_ID=%s\n' "$mid"
  sh "$LIB/parse-cmdline.sh"
} > "$tmp"

# root:kiosk 0640 keeps the bootstrap token off world-readable; fall back to 0644 if the kiosk group is
# absent (dev) so the user manager can still read it.
if chown "$OWNER" "$tmp" 2>/dev/null; then chmod 0640 "$tmp"; else chmod 0644 "$tmp"; fi
mv -f "$tmp" "$ENV_FILE"
exit 0
